@startuml

    package "Http" {
        [dataExchange]
        [updateTimer]
    }

    package "Ws" {
        [syncObject]
    }

    package "Models" {
        [User]
        [Session]
    }

    note top of dataExchange
        object to implement REST
        with server;
        get, push, insert, destroy
        to server;
    end note

    note top of updateTimer
        ajax updater to keep data updated;
        trigger GET request for dataExchange,
        on server data changed
    end note

    note top of syncObject
        websocket object, to update data on
        server and auto update data
        on client side
    end note


@enduml