@startuml


package "JavaScript" {
    [wss.js]
    [http.js]
}

package "Api Bridge" {
()HTTP
()WebSocket
}

:Client: -> [wss.js]
:Client: -> [http.js]

[wss.js] -> WebSocket:wss
[http.js] -> HTTP :ajax

package "Core" {
    [authorization] - Router
    ()Router - [ActivityLogger]
    Router -- [dataExchange]
    Router -- [EventsPusher]

}

WebSocket - Router
HTTP - Router

package "Modules" {
    [ModulesProvider]
    hghjgh - Users
}

package "Users" {
     [data]
     [privileges]
 }

i18n -> dataExchange
package "i18n" {

}

Git ->  ModulesProvider

package "Git" {
    [Repositories]
    [Commits]
    [Branches]
}

dataExchange -> hghjgh

    note top of wss.js
        <script src="//server/wss.js">
        script with api for
        web socket access
        to the data, session
    end note

    note top of http.js
        <script src="//server/http.js">
        script with api for http access
        to the data, session
    end note


@enduml